name: Deploy site to Production

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync --delete ./ s3://${{ secrets.AWS_BUCKET }}/aida-burlutckaia.online/production --exclude=".idea/*" --exclude ".git/*" --exclude ".github/*" --exclude "README*"