name: Deploy site to Staging

on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: aws s3 sync --delete ./ s3://${{ secrets.AWS_BUCKET }}/aida-burlutckaia.online/staging --exclude=".idea/*" --exclude ".git/*" --exclude "README*"